version: "3.8"

services:
  api:
    build: .
    container_name: telco_churn_api
    ports:
      - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs

  dashboard:
    build: .
    container_name: telco_churn_dashboard
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
